
# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zhd
    username: root
    password: root
 # redis:
  #  host: 59.110.241.109
   # port: 6379
   # password: 88888888.
   # database: 10
  #application:
   # name: test
#eureka:
 # client:
  #  service-url:
   #   defaultZone: http://localhost:8761/eureka/
ybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
 # global-config:
  #  db-config:
  #    id-type: id_worker
#debug: true
logging:
  level:
    com.base.myweb.mapper: debug